white_balance:
  generated_at: '2026-07-23T03:28:54.645451+00:00'
  generated_from_bag: bags/rosbag2_2026_07_22-15_02_21
  method: camera_to_camera_match
  reference_topic: /wrist_camera/color/image_raw
  roi:
    mode: full_image
  statistic: per_frame_trimmed_mean_then_median
  value_filter:
    min_value: 20
    max_value: 245
    min_pixels_per_frame: 100
    trim_percent: 5.0
    normalize_channel: g
  cameras:
    camera:
      topic: /camera/image_raw
      encoding: rgb8
      image_size:
      - 640
      - 480
      match_rgb_stat:
      - 125.0774
      - 169.6285
      - 122.775
      gains_rgb:
      - 1.361815
      - 1.0
      - 1.328469
      frames_seen: 151
      frames_used: 151
      valid_pixels: 38786131
    wrist_camera:
      topic: /wrist_camera/color/image_raw
      encoding: rgb8
      image_size:
      - 640
      - 480
      match_rgb_stat:
      - 147.7447
      - 147.1342
      - 141.4739
      gains_rgb:
      - 1.0
      - 1.0
      - 1.0
      frames_seen: 151
      frames_used: 151
      valid_pixels: 39027513
